#include "MainView.h"
#include "../hq_preload/dsp/cab/FactoryIrCatalog.h"

namespace
{
juce::var obj(){return juce::var(new juce::DynamicObject());}
float gf(juce::DynamicObject*o,const char*k,float f){const juce::Identifier id(k);return(o&&o->hasProperty(id))?(float)(double)o->getProperty(id):f;}
int gi(juce::DynamicObject*o,const char*k,int f){const juce::Identifier id(k);return(o&&o->hasProperty(id))?(int)o->getProperty(id):f;}
bool gb(juce::DynamicObject*o,const char*k,bool f){const juce::Identifier id(k);return(o&&o->hasProperty(id))?(bool)o->getProperty(id):f;}
}

MainView::MainView(AudioEngine&e):audioEngine(e),ampPage(e.getAmpEngine()),pedalPage(e.getHQEffectsRack()),cabPage(e.getCabMicEngine()),effectsPage(e.getHQEffectsRack()),performancePage(e),settingsPage(e.getDeviceManager())
{
 addAndMakeVisible(navigation);addAndMakeVisible(ampPage);addChildComponent(pedalPage);addChildComponent(cabPage);addChildComponent(effectsPage);addChildComponent(performancePage);addChildComponent(settingsPage);navigation.onPageSelected=[this](NavigationBar::Page p){showPage(p);};
 auto gain=[](juce::Slider&s,double lo,double hi,double v){s.setSliderStyle(juce::Slider::LinearHorizontal);s.setTextBoxStyle(juce::Slider::TextBoxRight,false,64,24);s.setRange(lo,hi,.1);s.setValue(v,juce::dontSendNotification);s.setNumDecimalPlacesToDisplay(1);s.setTextValueSuffix(" dB");};gain(inputGainSlider,-36,18,-6);gain(outputGainSlider,-60,6,-18);
 ampModeSelector.addItem("LEGACY 20",1);ampModeSelector.addItem("HQ 20",2);ampModeSelector.setSelectedId(1,juce::dontSendNotification);inputLabel.setText("INPUT",juce::dontSendNotification);outputLabel.setText("OUTPUT",juce::dontSendNotification);inputMeterLabel.setText("-100 dB",juce::dontSendNotification);outputMeterLabel.setText("-100 dB",juce::dontSendNotification);
 for(auto*l:{&inputLabel,&outputLabel})l->setColour(juce::Label::textColourId,juce::Colour::fromRGB(165,174,184));for(auto*l:{&inputMeterLabel,&outputMeterLabel})l->setColour(juce::Label::textColourId,juce::Colour::fromRGB(98,213,167));for(juce::Component*c:{static_cast<juce::Component*>(&inputGainSlider),static_cast<juce::Component*>(&outputGainSlider),static_cast<juce::Component*>(&ampModeSelector),static_cast<juce::Component*>(&bypassButton),static_cast<juce::Component*>(&inputLabel),static_cast<juce::Component*>(&outputLabel),static_cast<juce::Component*>(&inputMeterLabel),static_cast<juce::Component*>(&outputMeterLabel)})addAndMakeVisible(c);
 presetLabel.setText("PRESET",juce::dontSendNotification);presetLabel.setColour(juce::Label::textColourId,juce::Colour::fromRGB(222,110,58));presetSelector.setEditableText(true);presetSelector.setTextWhenNothingSelected("Type preset name");for(juce::Component*c:{static_cast<juce::Component*>(&presetLabel),static_cast<juce::Component*>(&presetSelector),static_cast<juce::Component*>(&presetSaveButton),static_cast<juce::Component*>(&presetDeleteButton)})addAndMakeVisible(c);
 inputGainSlider.onValueChange=[this]{audioEngine.setInputGainDb((float)inputGainSlider.getValue());};outputGainSlider.onValueChange=[this]{audioEngine.setOutputGainDb((float)outputGainSlider.getValue());};ampModeSelector.onChange=[this]{audioEngine.setAmpMode(ampModeSelector.getSelectedId()==2?SignalChain::AmpMode::hq:SignalChain::AmpMode::legacy);};bypassButton.onClick=[this]{audioEngine.setBypass(bypassButton.getToggleState());};presetSelector.onChange=[this]{if(!refreshingPresets)loadSelectedPreset();};presetSaveButton.onClick=[this]{saveCurrentPreset();};presetDeleteButton.onClick=[this]{deleteSelectedPreset();};
 audioEngine.setInputGainDb(-6);audioEngine.setOutputGainDb(-18);audioEngine.setAmpMode(SignalChain::AmpMode::legacy);refreshPresetList();showPage(NavigationBar::Page::amp);startTimerHz(15);
}
MainView::~MainView(){stopTimer();}
juce::File MainView::getPresetDirectory()const{auto d=juce::File::getSpecialLocation(juce::File::userApplicationDataDirectory).getChildFile("GuitarDSP-Pro").getChildFile("Presets");d.createDirectory();return d;}
juce::File MainView::getPresetFile(const juce::String&n)const{auto s=n.trim().removeCharacters("\\/:*?\"<>|");if(s.isEmpty())s="Preset";return getPresetDirectory().getChildFile(s+".json");}
void MainView::refreshPresetList(const juce::String&p){refreshingPresets=true;auto keep=p.isNotEmpty()?p:presetSelector.getText();presetSelector.clear(juce::dontSendNotification);int id=1;for(const auto&f:getPresetDirectory().findChildFiles(juce::File::findFiles,false,"*.json"))presetSelector.addItem(f.getFileNameWithoutExtension(),id++);if(keep.isNotEmpty())presetSelector.setText(keep,juce::dontSendNotification);refreshingPresets=false;}

juce::var MainView::capturePreset()const
{
 auto root=obj();auto*r=root.getDynamicObject();r->setProperty("version",5);r->setProperty("name",presetSelector.getText());r->setProperty("inputGainDb",inputGainSlider.getValue());r->setProperty("outputGainDb",outputGainSlider.getValue());r->setProperty("ampMode",(int)audioEngine.getAmpMode());r->setProperty("bypass",bypassButton.getToggleState());r->setProperty("outputMode",(int)audioEngine.getOutputMode());
 juce::Array<juce::var> legacy;for(const auto&p:audioEngine.getAmpEngine().getParameters()){auto v=obj();auto*o=v.getDynamicObject();o->setProperty("preHp",p.preHpHz);o->setProperty("preLp",p.preLpHz);o->setProperty("drive",p.drive);o->setProperty("bias",p.bias);o->setProperty("postLp",p.postLpHz);o->setProperty("output",p.output);o->setProperty("nonlinear",p.nonlinear);o->setProperty("clipShape",p.clipShape);legacy.add(v);}r->setProperty("legacyStages",juce::var(legacy));
 const auto&hp=audioEngine.getHQAmpEngine().getParameters();auto hq=obj();auto*ho=hq.getDynamicObject();juce::Array<juce::var>hs;for(const auto&p:hp.stage){auto v=obj();auto*o=v.getDynamicObject();o->setProperty("preHp",p.preHpHz);o->setProperty("preLp",p.preLpHz);o->setProperty("drive",p.drive);o->setProperty("bias",p.bias);o->setProperty("asym",p.asymmetry);o->setProperty("memory",p.memory);o->setProperty("postLp",p.postLpHz);o->setProperty("output",p.output);hs.add(v);}ho->setProperty("stages",juce::var(hs));ho->setProperty("bass",hp.bassDb);ho->setProperty("mid",hp.midDb);ho->setProperty("treble",hp.trebleDb);ho->setProperty("sag",hp.sag);ho->setProperty("sagRecovery",hp.sagRecoveryMs);ho->setProperty("damping",hp.damping);ho->setProperty("presence",hp.presence);ho->setProperty("resonance",hp.resonance);ho->setProperty("biasExcursion",hp.biasExcursion);ho->setProperty("transformerSat",hp.transformerSaturation);ho->setProperty("outputDb",hp.outputDb);ho->setProperty("jvmToneEnabled",hp.jvmToneStackEnabled);ho->setProperty("jvmBass",hp.jvmToneStack.bass);ho->setProperty("jvmMiddle",hp.jvmToneStack.middle);ho->setProperty("jvmTreble",hp.jvmToneStack.treble);ho->setProperty("jvmBassTaper",hp.jvmToneStack.bassTaper);ho->setProperty("jvmMiddleTaper",hp.jvmToneStack.middleTaper);ho->setProperty("jvmTrebleTaper",hp.jvmToneStack.trebleTaper);ho->setProperty("jvmR1Scale",hp.jvmToneStack.r1Scale);ho->setProperty("jvmR2Scale",hp.jvmToneStack.r2Scale);ho->setProperty("jvmC1Scale",hp.jvmToneStack.c1Scale);ho->setProperty("jvmC23Scale",hp.jvmToneStack.c23Scale);r->setProperty("hqAmp",hq);
 auto&rack=audioEngine.getHQEffectsRack();juce::Array<juce::var>pedals;for(int i=0;i<guitardsp::hq::HQEffectsRack::pedalSlots;++i){auto&p=rack.pedalSlot(i);auto v=obj();auto*o=v.getDynamicObject();o->setProperty("enabled",p.enabled.load());o->setProperty("model",p.model.load());o->setProperty("drive",p.drive.load());o->setProperty("tone",p.tone.load());o->setProperty("level",p.levelDb.load());o->setProperty("mix",p.mix.load());o->setProperty("aux1",p.aux1.load());o->setProperty("aux2",p.aux2.load());o->setProperty("aux3",p.aux3.load());o->setProperty("routeMask",p.routeMask.load());pedals.add(v);}r->setProperty("pedals",juce::var(pedals));
 auto gate=obj();auto*go=gate.getDynamicObject();auto&g=rack.gateControl();go->setProperty("mode",(int)rack.getDynamicsMode());go->setProperty("threshold",g.thresholdDb.load());go->setProperty("range",g.rangeDb.load());go->setProperty("ratio",g.ratio.load());go->setProperty("attack",g.attackMs.load());go->setProperty("hold",g.holdMs.load());go->setProperty("release",g.releaseMs.load());go->setProperty("hysteresis",g.hysteresisDb.load());go->setProperty("hp",g.sidechainHpHz.load());go->setProperty("lp",g.sidechainLpHz.load());r->setProperty("gate",gate);
 auto studio=obj();auto*so=studio.getDynamicObject();auto&sc=rack.studioCompControl();so->setProperty("threshold",sc.thresholdDb.load());so->setProperty("ratio",sc.ratio.load());so->setProperty("attack",sc.attackMs.load());so->setProperty("release",sc.releaseMs.load());so->setProperty("knee",sc.kneeDb.load());so->setProperty("makeup",sc.makeupDb.load());so->setProperty("mix",sc.mix.load());so->setProperty("hp",sc.sidechainHpHz.load());so->setProperty("rms",sc.rms.load());so->setProperty("autoRelease",sc.autoRelease.load());so->setProperty("autoMakeup",sc.autoMakeup.load());r->setProperty("studioComp",studio);
 auto guitar=obj();auto*gco=guitar.getDynamicObject();auto&gc=rack.guitarCompControl();gco->setProperty("sustain",gc.sustain.load());gco->setProperty("attack",gc.attack.load());gco->setProperty("blend",gc.blend.load());gco->setProperty("level",gc.levelDb.load());r->setProperty("guitarComp",guitar);
 auto pr=obj();auto*po=pr.getDynamicObject();auto&pc=rack.parallelRigControl();po->setProperty("enabled",pc.enabled.load());po->setProperty("autoLatency",pc.autoLatencyComp.load());po->setProperty("mainLevel",pc.mainLevelDb.load());po->setProperty("mainDelay",pc.mainDelayMs.load());po->setProperty("cleanEnabled",pc.cleanEnabled.load());po->setProperty("cleanLevel",pc.cleanLevelDb.load());po->setProperty("cleanHp",pc.cleanHpHz.load());po->setProperty("cleanLp",pc.cleanLpHz.load());po->setProperty("cleanPresence",pc.cleanPresenceDb.load());po->setProperty("cleanDrive",pc.cleanDrive.load());po->setProperty("cleanBass",pc.cleanBassDb.load());po->setProperty("cleanMid",pc.cleanMidDb.load());po->setProperty("cleanTreble",pc.cleanTrebleDb.load());po->setProperty("cleanDelay",pc.cleanDelayMs.load());po->setProperty("cleanInvert",pc.cleanInvert.load());po->setProperty("subEnabled",pc.subEnabled.load());po->setProperty("subLevel",pc.subLevelDb.load());po->setProperty("subHp",pc.subHpHz.load());po->setProperty("subLp",pc.subLpHz.load());po->setProperty("subBody",pc.subBodyDb.load());po->setProperty("subDrive",pc.subDrive.load());po->setProperty("subBass",pc.subBassDb.load());po->setProperty("subMid",pc.subMidDb.load());po->setProperty("subTreble",pc.subTrebleDb.load());po->setProperty("subTracking",pc.subTracking.load());po->setProperty("subTone",pc.subTone.load());po->setProperty("subSmooth",pc.subSmooth.load());po->setProperty("subDelay",pc.subDelayMs.load());po->setProperty("subInvert",pc.subInvert.load());r->setProperty("parallelRig",pr);
 auto il=obj();auto*ilo=il.getDynamicObject();auto&ic=audioEngine.getInputLoadingControl();ilo->setProperty("enabled",ic.enabled.load());ilo->setProperty("pickupR",ic.pickupResistanceOhm.load());ilo->setProperty("pickupL",ic.pickupInductanceH.load());ilo->setProperty("cableC",ic.cableCapacitancePf.load());ilo->setProperty("inputZ",ic.inputImpedanceOhm.load());ilo->setProperty("trim",ic.trimDb.load());r->setProperty("inputLoading",il);
 auto ep=obj();auto*epo=ep.getDynamicObject();auto&ec=audioEngine.getExpressionPitchControl();epo->setProperty("enabled",ec.enabled.load());epo->setProperty("routeMask",ec.routeMask.load());epo->setProperty("semitones",ec.semitones.load());epo->setProperty("expression",ec.expression.load());epo->setProperty("wet",ec.wet.load());epo->setProperty("dry",ec.dry.load());epo->setProperty("tracking",ec.tracking.load());epo->setProperty("tone",ec.tone.load());epo->setProperty("smooth",ec.smooth.load());r->setProperty("expressionPitch",ep);
 auto dd=obj();auto*ddo=dd.getDynamicObject();auto&dc=audioEngine.getDualDelayControl();ddo->setProperty("enabled",dc.enabled.load());ddo->setProperty("timeL",dc.timeLms.load());ddo->setProperty("timeR",dc.timeRms.load());ddo->setProperty("feedbackL",dc.feedbackL.load());ddo->setProperty("feedbackR",dc.feedbackR.load());ddo->setProperty("crossFeedback",dc.crossFeedback.load());ddo->setProperty("mix",dc.mix.load());ddo->setProperty("lowCut",dc.lowCutHz.load());ddo->setProperty("highCut",dc.highCutHz.load());ddo->setProperty("modRate",dc.modRateHz.load());ddo->setProperty("modDepth",dc.modDepthMs.load());r->setProperty("dualDelay",dd);
 juce::Array<juce::var>sa;auto&sw=audioEngine.getSceneSwitcher();for(int i=0;i<guitardsp::hq::SceneSwitcherHQ::sceneCount;++i){const auto&s=sw.scene(i);auto v=obj();auto*o=v.getDynamicObject();o->setProperty("parallel",s.parallelEnabled);o->setProperty("pitch",s.expressionPitchEnabled);o->setProperty("expression",s.expression);o->setProperty("semitones",s.pitchSemitones);o->setProperty("dualDelay",s.dualDelayEnabled);o->setProperty("main",s.mainDb);o->setProperty("clean",s.cleanDb);o->setProperty("sub",s.subDb);juce::Array<juce::var>re,rm;for(int j=0;j<4;++j){re.add(s.pedalEnabled[(size_t)j]);rm.add(s.pedalRouteMask[(size_t)j]);}o->setProperty("pedalEnabled",juce::var(re));o->setProperty("pedalRoutes",juce::var(rm));sa.add(v);}r->setProperty("scenes",juce::var(sa));
 auto mod=obj();auto*mo=mod.getDynamicObject();auto&m=rack.modulationControl();mo->setProperty("mode",(int)rack.getModulationMode());mo->setProperty("rate",m.rateHz.load());mo->setProperty("depth",m.depth.load());mo->setProperty("mix",m.mix.load());mo->setProperty("feedback",m.feedback.load());mo->setProperty("manual",m.manual.load());mo->setProperty("shape",m.shape.load());r->setProperty("mod",mod);
 auto de=obj();auto*deo=de.getDynamicObject();auto&d=rack.delayControl();deo->setProperty("enabled",rack.isDelayEnabled());deo->setProperty("type",d.flavor.load());deo->setProperty("time",d.timeMs.load());deo->setProperty("feedback",d.feedback.load());deo->setProperty("mix",d.mix.load());deo->setProperty("lowCut",d.lowCutHz.load());deo->setProperty("highCut",d.highCutHz.load());deo->setProperty("drive",d.drive.load());deo->setProperty("wow",d.wow.load());deo->setProperty("flutter",d.flutter.load());deo->setProperty("age",d.age.load());r->setProperty("delay",de);
 auto rvj=obj();auto*rvo=rvj.getDynamicObject();auto&rv=rack.reverbControl();rvo->setProperty("enabled",rack.isReverbEnabled());rvo->setProperty("type",rv.flavor.load());rvo->setProperty("size",rv.size.load());rvo->setProperty("decay",rv.decay.load());rvo->setProperty("damping",rv.damping.load());rvo->setProperty("preDelay",rv.preDelayMs.load());rvo->setProperty("mix",rv.mix.load());rvo->setProperty("mod",rv.mod.load());rvo->setProperty("drip",rv.drip.load());r->setProperty("reverb",rvj);
 const auto&cp=audioEngine.getCabMicEngine().getParameters();auto cab=obj();auto*co=cab.getDynamicObject();const auto irFile=audioEngine.getCabMicEngine().getExternalIrFile();co->setProperty("enabled",audioEngine.getCabMicEngine().isEnabled());co->setProperty("irEngine",(int)cp.irEngine);co->setProperty("externalIrSize",(int)cp.externalIrSize);co->setProperty("externalIrPath",irFile.getFullPathName());co->setProperty("factoryIrIndex",guitardsp::hq::FactoryIrCatalog::indexForFile(irFile));co->setProperty("irLevelDb",cp.irLevelDb);co->setProperty("polarityInvert",cp.polarityInvert);co->setProperty("cab",(int)cp.cab);co->setProperty("mic",(int)cp.mic);co->setProperty("position",cp.position);co->setProperty("distance",cp.distance);co->setProperty("resonance",cp.resonance);co->setProperty("lowCut",cp.lowCutHz);co->setProperty("highCut",cp.highCutHz);co->setProperty("mix",cp.mix);co->setProperty("lowVolumeFeel",cp.lowVolumeFeel);r->setProperty("cab",cab);return root;
}

bool MainView::applyPreset(const juce::var&preset)
{
 auto*r=preset.getDynamicObject();if(!r)return false;const int ver=gi(r,"version",1);const float in=gf(r,"inputGainDb",(float)inputGainSlider.getValue()),out=gf(r,"outputGainDb",(float)outputGainSlider.getValue());inputGainSlider.setValue(in,juce::dontSendNotification);outputGainSlider.setValue(out,juce::dontSendNotification);audioEngine.setInputGainDb(in);audioEngine.setOutputGainDb(out);const int am=juce::jlimit(0,1,gi(r,"ampMode",0));audioEngine.setAmpMode((SignalChain::AmpMode)am);ampModeSelector.setSelectedId(am+1,juce::dontSendNotification);const bool bp=gb(r,"bypass",false);bypassButton.setToggleState(bp,juce::dontSendNotification);audioEngine.setBypass(bp);audioEngine.setOutputMode((SignalChain::OutputMode)juce::jlimit(0,1,gi(r,"outputMode",0)));
 if(auto*a=r->getProperty("legacyStages").getArray()){auto p=audioEngine.getAmpEngine().getParameters();for(int i=0;i<juce::jmin((int)a->size(),AmpEngine::numStages);++i){auto*o=(*a)[i].getDynamicObject();auto&s=p[(size_t)i];s.preHpHz=gf(o,"preHp",s.preHpHz);s.preLpHz=gf(o,"preLp",s.preLpHz);s.drive=gf(o,"drive",s.drive);s.bias=gf(o,"bias",s.bias);s.postLpHz=gf(o,"postLp",s.postLpHz);s.output=gf(o,"output",s.output);s.nonlinear=gf(o,"nonlinear",s.nonlinear);s.clipShape=gf(o,"clipShape",s.clipShape);}audioEngine.getAmpEngine().setParameters(p);}
 if(auto*o=r->getProperty("hqAmp").getDynamicObject()){auto p=audioEngine.getHQAmpEngine().getParameters();if(auto*a=o->getProperty("stages").getArray())for(int i=0;i<juce::jmin((int)a->size(),20);++i){auto*so=(*a)[i].getDynamicObject();auto&s=p.stage[(size_t)i];s.preHpHz=gf(so,"preHp",s.preHpHz);s.preLpHz=gf(so,"preLp",s.preLpHz);s.drive=gf(so,"drive",s.drive);s.bias=gf(so,"bias",s.bias);s.asymmetry=gf(so,"asym",s.asymmetry);s.memory=gf(so,"memory",s.memory);s.postLpHz=gf(so,"postLp",s.postLpHz);s.output=gf(so,"output",s.output);}p.bassDb=gf(o,"bass",p.bassDb);p.midDb=gf(o,"mid",p.midDb);p.trebleDb=gf(o,"treble",p.trebleDb);p.sag=gf(o,"sag",p.sag);p.sagRecoveryMs=gf(o,"sagRecovery",p.sagRecoveryMs);p.damping=gf(o,"damping",p.damping);p.presence=gf(o,"presence",p.presence);p.resonance=gf(o,"resonance",p.resonance);p.biasExcursion=gf(o,"biasExcursion",p.biasExcursion);p.transformerSaturation=gf(o,"transformerSat",p.transformerSaturation);p.outputDb=gf(o,"outputDb",p.outputDb);p.jvmToneStackEnabled=gb(o,"jvmToneEnabled",p.jvmToneStackEnabled);p.jvmToneStack.bass=gf(o,"jvmBass",p.jvmToneStack.bass);p.jvmToneStack.middle=gf(o,"jvmMiddle",p.jvmToneStack.middle);p.jvmToneStack.treble=gf(o,"jvmTreble",p.jvmToneStack.treble);p.jvmToneStack.bassTaper=gf(o,"jvmBassTaper",p.jvmToneStack.bassTaper);p.jvmToneStack.middleTaper=gf(o,"jvmMiddleTaper",p.jvmToneStack.middleTaper);p.jvmToneStack.trebleTaper=gf(o,"jvmTrebleTaper",p.jvmToneStack.trebleTaper);p.jvmToneStack.r1Scale=gf(o,"jvmR1Scale",p.jvmToneStack.r1Scale);p.jvmToneStack.r2Scale=gf(o,"jvmR2Scale",p.jvmToneStack.r2Scale);p.jvmToneStack.c1Scale=gf(o,"jvmC1Scale",p.jvmToneStack.c1Scale);p.jvmToneStack.c23Scale=gf(o,"jvmC23Scale",p.jvmToneStack.c23Scale);audioEngine.getHQAmpEngine().setParameters(p);}
 auto&rack=audioEngine.getHQEffectsRack();if(auto*a=r->getProperty("pedals").getArray())for(int i=0;i<juce::jmin((int)a->size(),guitardsp::hq::HQEffectsRack::pedalSlots);++i){auto*o=(*a)[i].getDynamicObject();auto&p=rack.pedalSlot(i);p.enabled.store(gb(o,"enabled",p.enabled.load()));p.model.store(juce::jlimit(0,9,gi(o,"model",p.model.load())));p.drive.store(gf(o,"drive",p.drive.load()));p.tone.store(gf(o,"tone",p.tone.load()));p.levelDb.store(gf(o,"level",p.levelDb.load()));p.mix.store(gf(o,"mix",p.mix.load()));p.aux1.store(gf(o,"aux1",p.aux1.load()));p.aux2.store(gf(o,"aux2",p.aux2.load()));p.aux3.store(gf(o,"aux3",p.aux3.load()));p.routeMask.store(juce::jlimit(1,7,gi(o,"routeMask",guitardsp::hq::HQEffectsRack::routeMain)));}
 if(auto*o=r->getProperty("gate").getDynamicObject()){auto&g=rack.gateControl();rack.setDynamicsMode((guitardsp::hq::HQEffectsRack::DynamicsMode)juce::jlimit(0,3,gi(o,"mode",(int)rack.getDynamicsMode())));g.thresholdDb.store(gf(o,"threshold",g.thresholdDb.load()));g.rangeDb.store(gf(o,"range",g.rangeDb.load()));g.ratio.store(gf(o,"ratio",g.ratio.load()));g.attackMs.store(gf(o,"attack",g.attackMs.load()));g.holdMs.store(gf(o,"hold",g.holdMs.load()));g.releaseMs.store(gf(o,"release",g.releaseMs.load()));g.hysteresisDb.store(gf(o,"hysteresis",g.hysteresisDb.load()));g.sidechainHpHz.store(gf(o,"hp",g.sidechainHpHz.load()));g.sidechainLpHz.store(gf(o,"lp",g.sidechainLpHz.load()));}
 if(auto*o=r->getProperty("studioComp").getDynamicObject()){auto&c=rack.studioCompControl();c.thresholdDb.store(gf(o,"threshold",c.thresholdDb.load()));c.ratio.store(gf(o,"ratio",c.ratio.load()));c.attackMs.store(gf(o,"attack",c.attackMs.load()));c.releaseMs.store(gf(o,"release",c.releaseMs.load()));c.kneeDb.store(gf(o,"knee",c.kneeDb.load()));c.makeupDb.store(gf(o,"makeup",c.makeupDb.load()));c.mix.store(gf(o,"mix",c.mix.load()));c.sidechainHpHz.store(gf(o,"hp",c.sidechainHpHz.load()));c.rms.store(gb(o,"rms",c.rms.load()));c.autoRelease.store(gb(o,"autoRelease",c.autoRelease.load()));c.autoMakeup.store(gb(o,"autoMakeup",c.autoMakeup.load()));}
 if(auto*o=r->getProperty("guitarComp").getDynamicObject()){auto&c=rack.guitarCompControl();c.sustain.store(gf(o,"sustain",c.sustain.load()));c.attack.store(gf(o,"attack",c.attack.load()));c.blend.store(gf(o,"blend",c.blend.load()));c.levelDb.store(gf(o,"level",c.levelDb.load()));}
 auto&pc=rack.parallelRigControl();if(auto*o=r->getProperty("parallelRig").getDynamicObject()){pc.enabled.store(gb(o,"enabled",false));pc.autoLatencyComp.store(gb(o,"autoLatency",true));pc.mainLevelDb.store(gf(o,"mainLevel",0));pc.mainDelayMs.store(gf(o,"mainDelay",0));pc.cleanEnabled.store(gb(o,"cleanEnabled",true));pc.cleanLevelDb.store(gf(o,"cleanLevel",-12));pc.cleanHpHz.store(gf(o,"cleanHp",650));pc.cleanLpHz.store(gf(o,"cleanLp",14500));pc.cleanPresenceDb.store(gf(o,"cleanPresence",4));pc.cleanDrive.store(gf(o,"cleanDrive",.08f));pc.cleanBassDb.store(gf(o,"cleanBass",0));pc.cleanMidDb.store(gf(o,"cleanMid",-1));pc.cleanTrebleDb.store(gf(o,"cleanTreble",2.5f));pc.cleanDelayMs.store(gf(o,"cleanDelay",0));pc.cleanInvert.store(gb(o,"cleanInvert",false));pc.subEnabled.store(gb(o,"subEnabled",true));pc.subLevelDb.store(gf(o,"subLevel",-8));pc.subHpHz.store(gf(o,"subHp",32));pc.subLpHz.store(gf(o,"subLp",3200));pc.subBodyDb.store(gf(o,"subBody",3));pc.subDrive.store(gf(o,"subDrive",.34f));pc.subBassDb.store(gf(o,"subBass",2));pc.subMidDb.store(gf(o,"subMid",.5f));pc.subTrebleDb.store(gf(o,"subTreble",-2));pc.subTracking.store(gf(o,"subTracking",.72f));pc.subTone.store(gf(o,"subTone",.62f));pc.subSmooth.store(gf(o,"subSmooth",.68f));pc.subDelayMs.store(gf(o,"subDelay",0));pc.subInvert.store(gb(o,"subInvert",false));}else pc.enabled.store(false);
 auto&ic=audioEngine.getInputLoadingControl();if(auto*o=r->getProperty("inputLoading").getDynamicObject()){ic.enabled.store(gb(o,"enabled",false));ic.pickupResistanceOhm.store(gf(o,"pickupR",6500));ic.pickupInductanceH.store(gf(o,"pickupL",3.2f));ic.cableCapacitancePf.store(gf(o,"cableC",470));ic.inputImpedanceOhm.store(gf(o,"inputZ",1000000));ic.trimDb.store(gf(o,"trim",0));}else ic.enabled.store(false);
 auto&ec=audioEngine.getExpressionPitchControl();if(auto*o=r->getProperty("expressionPitch").getDynamicObject()){ec.enabled.store(gb(o,"enabled",false));ec.routeMask.store(juce::jlimit(1,7,gi(o,"routeMask",1)));ec.semitones.store(gf(o,"semitones",0));ec.expression.store(gf(o,"expression",1));ec.wet.store(gf(o,"wet",1));ec.dry.store(gf(o,"dry",0));ec.tracking.store(gf(o,"tracking",.55f));ec.tone.store(gf(o,"tone",.75f));ec.smooth.store(gf(o,"smooth",.60f));}else ec.enabled.store(false);
 auto&dc=audioEngine.getDualDelayControl();if(auto*o=r->getProperty("dualDelay").getDynamicObject()){dc.enabled.store(gb(o,"enabled",false));dc.timeLms.store(gf(o,"timeL",280));dc.timeRms.store(gf(o,"timeR",420));dc.feedbackL.store(gf(o,"feedbackL",.28f));dc.feedbackR.store(gf(o,"feedbackR",.32f));dc.crossFeedback.store(gf(o,"crossFeedback",.12f));dc.mix.store(gf(o,"mix",.20f));dc.lowCutHz.store(gf(o,"lowCut",120));dc.highCutHz.store(gf(o,"highCut",9000));dc.modRateHz.store(gf(o,"modRate",.35f));dc.modDepthMs.store(gf(o,"modDepth",.7f));}else dc.enabled.store(false);
 if(auto*a=r->getProperty("scenes").getArray()){auto&sw=audioEngine.getSceneSwitcher();for(int i=0;i<juce::jmin((int)a->size(),guitardsp::hq::SceneSwitcherHQ::sceneCount);++i){auto*o=(*a)[i].getDynamicObject();auto&s=sw.scene(i);s.parallelEnabled=gb(o,"parallel",s.parallelEnabled);s.expressionPitchEnabled=gb(o,"pitch",s.expressionPitchEnabled);s.expression=gf(o,"expression",s.expression);s.pitchSemitones=gf(o,"semitones",s.pitchSemitones);s.dualDelayEnabled=gb(o,"dualDelay",s.dualDelayEnabled);s.mainDb=gf(o,"main",s.mainDb);s.cleanDb=gf(o,"clean",s.cleanDb);s.subDb=gf(o,"sub",s.subDb);if(auto*re=o->getProperty("pedalEnabled").getArray())for(int j=0;j<juce::jmin(4,(int)re->size());++j)s.pedalEnabled[(size_t)j]=(bool)(*re)[j];if(auto*rm=o->getProperty("pedalRoutes").getArray())for(int j=0;j<juce::jmin(4,(int)rm->size());++j)s.pedalRouteMask[(size_t)j]=juce::jlimit(1,7,(int)(*rm)[j]);}}
 if(auto*o=r->getProperty("mod").getDynamicObject()){auto&m=rack.modulationControl();rack.setModulationMode((guitardsp::hq::HQEffectsRack::ModulationMode)juce::jlimit(0,5,gi(o,"mode",(int)rack.getModulationMode())));m.rateHz.store(gf(o,"rate",m.rateHz.load()));m.depth.store(gf(o,"depth",m.depth.load()));m.mix.store(gf(o,"mix",m.mix.load()));m.feedback.store(gf(o,"feedback",m.feedback.load()));m.manual.store(gf(o,"manual",m.manual.load()));m.shape.store(gf(o,"shape",m.shape.load()));}
 if(auto*o=r->getProperty("delay").getDynamicObject()){auto&d=rack.delayControl();rack.setDelayEnabled(gb(o,"enabled",rack.isDelayEnabled()));d.flavor.store(juce::jlimit(0,2,gi(o,"type",d.flavor.load())));d.timeMs.store(gf(o,"time",d.timeMs.load()));d.feedback.store(gf(o,"feedback",d.feedback.load()));d.mix.store(gf(o,"mix",d.mix.load()));d.lowCutHz.store(gf(o,"lowCut",d.lowCutHz.load()));d.highCutHz.store(gf(o,"highCut",d.highCutHz.load()));d.drive.store(gf(o,"drive",d.drive.load()));d.wow.store(gf(o,"wow",d.wow.load()));d.flutter.store(gf(o,"flutter",d.flutter.load()));d.age.store(gf(o,"age",d.age.load()));}
 if(auto*o=r->getProperty("reverb").getDynamicObject()){auto&v=rack.reverbControl();rack.setReverbEnabled(gb(o,"enabled",rack.isReverbEnabled()));v.flavor.store(juce::jlimit(0,3,gi(o,"type",v.flavor.load())));v.size.store(gf(o,"size",v.size.load()));v.decay.store(gf(o,"decay",v.decay.load()));v.damping.store(gf(o,"damping",v.damping.load()));v.preDelayMs.store(gf(o,"preDelay",v.preDelayMs.load()));v.mix.store(gf(o,"mix",v.mix.load()));v.mod.store(gf(o,"mod",v.mod.load()));v.drip.store(gf(o,"drip",v.drip.load()));}
 if(auto*o=r->getProperty("cab").getDynamicObject()){auto&ce=audioEngine.getCabMicEngine();auto p=ce.getParameters();p.irEngine=(guitardsp::hq::CabIrEngine)juce::jlimit(0,2,gi(o,"irEngine",0));p.externalIrSize=(guitardsp::hq::ExternalIrSize)juce::jlimit(0,2,gi(o,"externalIrSize",(int)p.externalIrSize));p.irLevelDb=gf(o,"irLevelDb",p.irLevelDb);p.polarityInvert=gb(o,"polarityInvert",p.polarityInvert);p.cab=(guitardsp::hq::CabType)juce::jlimit(0,3,gi(o,"cab",(int)p.cab));p.mic=(guitardsp::hq::MicType)juce::jlimit(0,2,gi(o,"mic",(int)p.mic));p.position=gf(o,"position",p.position);p.distance=gf(o,"distance",p.distance);p.resonance=gf(o,"resonance",p.resonance);p.lowCutHz=gf(o,"lowCut",p.lowCutHz);p.highCutHz=gf(o,"highCut",p.highCutHz);p.mix=gf(o,"mix",p.mix);p.lowVolumeFeel=gf(o,"lowVolumeFeel",p.lowVolumeFeel);ce.setParameters(p);if(p.irEngine==guitardsp::hq::CabIrEngine::external){const int fi=gi(o,"factoryIrIndex",-1);juce::File f=fi>=0?guitardsp::hq::FactoryIrCatalog::fileForIndex(fi):juce::File(o->getProperty("externalIrPath").toString());f=guitardsp::hq::FactoryIrCatalog::resolveFile(f);if(f.existsAsFile())ce.loadExternalImpulse(f);}ce.setEnabled(gb(o,"enabled",ce.isEnabled()));}
 if(ver<5){pc.enabled.store(false);ic.enabled.store(false);ec.enabled.store(false);dc.enabled.store(false);audioEngine.setOutputMode(SignalChain::OutputMode::stereoMix);for(int i=0;i<guitardsp::hq::HQEffectsRack::pedalSlots;++i)rack.pedalSlot(i).routeMask.store(guitardsp::hq::HQEffectsRack::routeMain);}
 refreshPagesFromEngine();return true;
}

void MainView::saveCurrentPreset(){auto n=presetSelector.getText().trim();if(n.isEmpty()||n=="Type preset name")n="Preset 1";if(getPresetFile(n).replaceWithText(juce::JSON::toString(capturePreset(),false)))refreshPresetList(n);}
void MainView::loadSelectedPreset(){auto n=presetSelector.getText().trim();auto f=getPresetFile(n);if(!f.existsAsFile())return;auto p=juce::JSON::parse(f.loadFileAsString());if(applyPreset(p))presetSelector.setText(n,juce::dontSendNotification);}
void MainView::deleteSelectedPreset(){auto f=getPresetFile(presetSelector.getText().trim());if(f.existsAsFile())f.deleteFile();refreshPresetList();}
void MainView::refreshPagesFromEngine(){ampPage.refreshFromEngine();pedalPage.refreshFromEngine();cabPage.refreshFromEngine();effectsPage.refreshFromEngine();performancePage.refreshFromEngine();}
void MainView::paint(juce::Graphics&g){g.fillAll(juce::Colour::fromRGB(9,12,16));auto r=getLocalBounds();auto h=r.removeFromTop(76);g.setColour(juce::Colour::fromRGB(14,18,24));g.fillRect(h);g.setColour(juce::Colours::white);g.setFont(juce::Font(24.0f,juce::Font::bold));g.drawText("GuitarDSP-Pro",h.removeFromLeft(250).reduced(20,0),juce::Justification::centredLeft);g.setColour(juce::Colour::fromRGB(222,110,58));g.setFont(juce::Font(13.0f));g.drawText("AMP LAB / MULTI-RIG",h.removeFromLeft(190),juce::Justification::centredLeft);g.setColour(juce::Colour::fromRGB(12,16,21));g.fillRect(0,76,getWidth(),38);}
void MainView::resized(){auto r=getLocalBounds();auto h=r.removeFromTop(76);auto c=h.removeFromRight(845).reduced(8,8);inputLabel.setBounds(c.removeFromLeft(48));inputGainSlider.setBounds(c.removeFromLeft(170).reduced(3,10));inputMeterLabel.setBounds(c.removeFromLeft(70));c.removeFromLeft(5);outputLabel.setBounds(c.removeFromLeft(58));outputGainSlider.setBounds(c.removeFromLeft(170).reduced(3,10));outputMeterLabel.setBounds(c.removeFromLeft(70));ampModeSelector.setBounds(c.removeFromLeft(135).reduced(4,10));bypassButton.setBounds(c.removeFromLeft(90).reduced(5,10));auto pb=r.removeFromTop(38).reduced(14,4);presetLabel.setBounds(pb.removeFromLeft(58));presetSelector.setBounds(pb.removeFromLeft(260));pb.removeFromLeft(6);presetSaveButton.setBounds(pb.removeFromLeft(72));pb.removeFromLeft(6);presetDeleteButton.setBounds(pb.removeFromLeft(82));navigation.setBounds(r.removeFromTop(54));if(visiblePage)visiblePage->setBounds(r.reduced(14));}
void MainView::showPage(NavigationBar::Page p){juce::Component*n=nullptr;switch(p){case NavigationBar::Page::amp:n=&ampPage;break;case NavigationBar::Page::pedal:n=&pedalPage;break;case NavigationBar::Page::cab:n=&cabPage;break;case NavigationBar::Page::effects:n=&effectsPage;break;case NavigationBar::Page::performance:n=&performancePage;break;case NavigationBar::Page::settings:n=&settingsPage;break;}if(visiblePage)visiblePage->setVisible(false);visiblePage=n;if(n){n->setVisible(true);n->toFront(false);}resized();}
void MainView::timerCallback(){const float i=juce::jmax(audioEngine.getInputPeak(0),audioEngine.getInputPeak(1)),o=juce::jmax(audioEngine.getOutputPeak(0),audioEngine.getOutputPeak(1));inputMeterLabel.setText(juce::String(i,1)+" dB",juce::dontSendNotification);outputMeterLabel.setText(juce::String(o,1)+" dB",juce::dontSendNotification);}
