#include "MainView.h"

namespace
{
juce::var makeObject(){return juce::var(new juce::DynamicObject());}
float getFloat(juce::DynamicObject*o,const char*k,float f){const juce::Identifier id(k);return(o&&o->hasProperty(id))?(float)(double)o->getProperty(id):f;}
int getInt(juce::DynamicObject*o,const char*k,int f){const juce::Identifier id(k);return(o&&o->hasProperty(id))?(int)o->getProperty(id):f;}
bool getBool(juce::DynamicObject*o,const char*k,bool f){const juce::Identifier id(k);return(o&&o->hasProperty(id))?(bool)o->getProperty(id):f;}
}

MainView::MainView(AudioEngine& engine)
    : audioEngine(engine), ampPage(engine.getAmpEngine()), pedalPage(engine.getHQEffectsRack()),
      cabPage(engine.getCabMicEngine()), effectsPage(engine.getHQEffectsRack()),
      performancePage(engine), settingsPage(engine.getDeviceManager())
{
    addAndMakeVisible(navigation);addAndMakeVisible(ampPage);addChildComponent(pedalPage);addChildComponent(cabPage);addChildComponent(effectsPage);addChildComponent(performancePage);addChildComponent(settingsPage);
    navigation.onPageSelected=[this](NavigationBar::Page p){showPage(p);};
    auto gain=[](juce::Slider&s,double lo,double hi,double v){s.setSliderStyle(juce::Slider::LinearHorizontal);s.setTextBoxStyle(juce::Slider::TextBoxRight,false,64,24);s.setRange(lo,hi,.1);s.setValue(v,juce::dontSendNotification);s.setNumDecimalPlacesToDisplay(1);s.setTextValueSuffix(" dB");};
    gain(inputGainSlider,-36,18,-6);gain(outputGainSlider,-60,6,-18);
    ampModeSelector.addItem("LEGACY 20",1);ampModeSelector.addItem("HQ 20",2);ampModeSelector.setSelectedId(1,juce::dontSendNotification);
    inputLabel.setText("INPUT",juce::dontSendNotification);outputLabel.setText("OUTPUT",juce::dontSendNotification);inputMeterLabel.setText("-100 dB",juce::dontSendNotification);outputMeterLabel.setText("-100 dB",juce::dontSendNotification);
    for(auto*l:{&inputLabel,&outputLabel})l->setColour(juce::Label::textColourId,juce::Colour::fromRGB(165,174,184));for(auto*l:{&inputMeterLabel,&outputMeterLabel})l->setColour(juce::Label::textColourId,juce::Colour::fromRGB(98,213,167));
    for(auto*c:{(juce::Component*)&inputGainSlider,&outputGainSlider,&ampModeSelector,&bypassButton,&inputLabel,&outputLabel,&inputMeterLabel,&outputMeterLabel})addAndMakeVisible(c);
    presetLabel.setText("PRESET",juce::dontSendNotification);presetLabel.setColour(juce::Label::textColourId,juce::Colour::fromRGB(222,110,58));presetLabel.setFont(juce::Font(12.0f,juce::Font::bold));presetSelector.setEditableText(true);presetSelector.setTextWhenNothingSelected("Type preset name");
    for(auto*c:{(juce::Component*)&presetLabel,&presetSelector,&presetSaveButton,&presetDeleteButton})addAndMakeVisible(c);
    inputGainSlider.onValueChange=[this]{audioEngine.setInputGainDb((float)inputGainSlider.getValue());};outputGainSlider.onValueChange=[this]{audioEngine.setOutputGainDb((float)outputGainSlider.getValue());};
    ampModeSelector.onChange=[this]{audioEngine.setAmpMode(ampModeSelector.getSelectedId()==2?SignalChain::AmpMode::hq:SignalChain::AmpMode::legacy);};bypassButton.onClick=[this]{audioEngine.setBypass(bypassButton.getToggleState());};
    presetSelector.onChange=[this]{if(!refreshingPresets)loadSelectedPreset();};presetSaveButton.onClick=[this]{saveCurrentPreset();};presetDeleteButton.onClick=[this]{deleteSelectedPreset();};
    audioEngine.setInputGainDb(-6);audioEngine.setOutputGainDb(-18);audioEngine.setAmpMode(SignalChain::AmpMode::legacy);refreshPresetList();showPage(NavigationBar::Page::amp);startTimerHz(15);
}

MainView::~MainView(){stopTimer();}
juce::File MainView::getPresetDirectory()const{auto d=juce::File::getSpecialLocation(juce::File::userApplicationDataDirectory).getChildFile("GuitarDSP-Pro").getChildFile("Presets");d.createDirectory();return d;}
juce::File MainView::getPresetFile(const juce::String&n)const{auto s=n.trim().removeCharacters("\\/:*?\"<>|");if(s.isEmpty())s="Preset";return getPresetDirectory().getChildFile(s+".json");}
void MainView::refreshPresetList(const juce::String&p){refreshingPresets=true;auto keep=p.isNotEmpty()?p:presetSelector.getText();presetSelector.clear(juce::dontSendNotification);int id=1;for(const auto&f:getPresetDirectory().findChildFiles(juce::File::findFiles,false,"*.json"))presetSelector.addItem(f.getFileNameWithoutExtension(),id++);if(keep.isNotEmpty())presetSelector.setText(keep,juce::dontSendNotification);refreshingPresets=false;}

juce::var MainView::capturePreset()const
{
    auto root=makeObject();auto*r=root.getDynamicObject();r->setProperty("version",3);r->setProperty("name",presetSelector.getText());r->setProperty("inputGainDb",inputGainSlider.getValue());r->setProperty("outputGainDb",outputGainSlider.getValue());r->setProperty("ampMode",(int)audioEngine.getAmpMode());r->setProperty("bypass",bypassButton.getToggleState());r->setProperty("outputMode",(int)audioEngine.getOutputMode());
    juce::Array<juce::var> legacy;for(const auto&p:audioEngine.getAmpEngine().getParameters()){auto v=makeObject();auto*o=v.getDynamicObject();o->setProperty("preHp",p.preHpHz);o->setProperty("preLp",p.preLpHz);o->setProperty("drive",p.drive);o->setProperty("bias",p.bias);o->setProperty("postLp",p.postLpHz);o->setProperty("output",p.output);o->setProperty("nonlinear",p.nonlinear);o->setProperty("clipShape",p.clipShape);legacy.add(v);}r->setProperty("legacyStages",juce::var(legacy));
    const auto&hp=audioEngine.getHQAmpEngine().getParameters();auto hq=makeObject();auto*ho=hq.getDynamicObject();juce::Array<juce::var>hs;for(const auto&p:hp.stage){auto v=makeObject();auto*o=v.getDynamicObject();o->setProperty("preHp",p.preHpHz);o->setProperty("preLp",p.preLpHz);o->setProperty("drive",p.drive);o->setProperty("bias",p.bias);o->setProperty("asym",p.asymmetry);o->setProperty("memory",p.memory);o->setProperty("postLp",p.postLpHz);o->setProperty("output",p.output);hs.add(v);}ho->setProperty("stages",juce::var(hs));ho->setProperty("bass",hp.bassDb);ho->setProperty("mid",hp.midDb);ho->setProperty("treble",hp.trebleDb);ho->setProperty("sag",hp.sag);ho->setProperty("sagRecovery",hp.sagRecoveryMs);ho->setProperty("damping",hp.damping);ho->setProperty("presence",hp.presence);ho->setProperty("biasExcursion",hp.biasExcursion);ho->setProperty("transformerSat",hp.transformerSaturation);ho->setProperty("outputDb",hp.outputDb);r->setProperty("hqAmp",hq);
    auto&rack=audioEngine.getHQEffectsRack();juce::Array<juce::var>pedals;for(int i=0;i<guitardsp::hq::HQEffectsRack::pedalSlots;++i){auto&p=rack.pedalSlot(i);auto v=makeObject();auto*o=v.getDynamicObject();o->setProperty("enabled",p.enabled.load());o->setProperty("model",p.model.load());o->setProperty("drive",p.drive.load());o->setProperty("tone",p.tone.load());o->setProperty("level",p.levelDb.load());o->setProperty("mix",p.mix.load());o->setProperty("aux1",p.aux1.load());o->setProperty("aux2",p.aux2.load());o->setProperty("aux3",p.aux3.load());o->setProperty("routeMask",p.routeMask.load());pedals.add(v);}r->setProperty("pedals",juce::var(pedals));
    auto gate=makeObject();auto*go=gate.getDynamicObject();auto&g=rack.gateControl();go->setProperty("mode",(int)rack.getDynamicsMode());go->setProperty("threshold",g.thresholdDb.load());go->setProperty("range",g.rangeDb.load());go->setProperty("ratio",g.ratio.load());go->setProperty("attack",g.attackMs.load());go->setProperty("hold",g.holdMs.load());go->setProperty("release",g.releaseMs.load());go->setProperty("hysteresis",g.hysteresisDb.load());go->setProperty("hp",g.sidechainHpHz.load());go->setProperty("lp",g.sidechainLpHz.load());r->setProperty("gate",gate);
    auto gcj=makeObject();auto*gco=gcj.getDynamicObject();auto&gc=rack.guitarCompControl();gco->setProperty("sustain",gc.sustain.load());gco->setProperty("attack",gc.attack.load());gco->setProperty("blend",gc.blend.load());gco->setProperty("level",gc.levelDb.load());r->setProperty("guitarComp",gcj);
    auto pr=makeObject();auto*po=pr.getDynamicObject();auto&pc=rack.parallelRigControl();po->setProperty("enabled",pc.enabled.load());po->setProperty("autoLatency",pc.autoLatencyComp.load());po->setProperty("mainLevel",pc.mainLevelDb.load());po->setProperty("mainDelay",pc.mainDelayMs.load());po->setProperty("cleanEnabled",pc.cleanEnabled.load());po->setProperty("cleanLevel",pc.cleanLevelDb.load());po->setProperty("cleanHp",pc.cleanHpHz.load());po->setProperty("cleanLp",pc.cleanLpHz.load());po->setProperty("cleanPresence",pc.cleanPresenceDb.load());po->setProperty("cleanDrive",pc.cleanDrive.load());po->setProperty("cleanBass",pc.cleanBassDb.load());po->setProperty("cleanMid",pc.cleanMidDb.load());po->setProperty("cleanTreble",pc.cleanTrebleDb.load());po->setProperty("cleanDelay",pc.cleanDelayMs.load());po->setProperty("cleanInvert",pc.cleanInvert.load());po->setProperty("subEnabled",pc.subEnabled.load());po->setProperty("subLevel",pc.subLevelDb.load());po->setProperty("subHp",pc.subHpHz.load());po->setProperty("subLp",pc.subLpHz.load());po->setProperty("subBody",pc.subBodyDb.load());po->setProperty("subDrive",pc.subDrive.load());po->setProperty("subBass",pc.subBassDb.load());po->setProperty("subMid",pc.subMidDb.load());po->setProperty("subTreble",pc.subTrebleDb.load());po->setProperty("subTracking",pc.subTracking.load());po->setProperty("subTone",pc.subTone.load());po->setProperty("subSmooth",pc.subSmooth.load());po->setProperty("subDelay",pc.subDelayMs.load());po->setProperty("subInvert",pc.subInvert.load());r->setProperty("parallelRig",pr);
    auto il=makeObject();auto*ilo=il.getDynamicObject();auto&ic=audioEngine.getInputLoadingControl();ilo->setProperty("enabled",ic.enabled.load());ilo->setProperty("pickupR",ic.pickupResistanceOhm.load());ilo->setProperty("pickupL",ic.pickupInductanceH.load());ilo->setProperty("cableC",ic.cableCapacitancePf.load());ilo->setProperty("inputZ",ic.inputImpedanceOhm.load());ilo->setProperty("trim",ic.trimDb.load());r->setProperty("inputLoading",il);
    auto ep=makeObject();auto*epo=ep.getDynamicObject();auto&ec=audioEngine.getExpressionPitchControl();epo->setProperty("enabled",ec.enabled.load());epo->setProperty("routeMask",ec.routeMask.load());epo->setProperty("semitones",ec.semitones.load());epo->setProperty("expression",ec.expression.load());epo->setProperty("wet",ec.wet.load());epo->setProperty("dry",ec.dry.load());epo->setProperty("tracking",ec.tracking.load());epo->setProperty("tone",ec.tone.load());epo->setProperty("smooth",ec.smooth.load());r->setProperty("expressionPitch",ep);
    auto dd=makeObject();auto*ddo=dd.getDynamicObject();auto&dc=audioEngine.getDualDelayControl();ddo->setProperty("enabled",dc.enabled.load());ddo->setProperty("timeL",dc.timeLms.load());ddo->setProperty("timeR",dc.timeRms.load());ddo->setProperty("feedbackL",dc.feedbackL.load());ddo->setProperty("feedbackR",dc.feedbackR.load());ddo->setProperty("crossFeedback",dc.crossFeedback.load());ddo->setProperty("mix",dc.mix.load());ddo->setProperty("lowCut",dc.lowCutHz.load());ddo->setProperty("highCut",dc.highCutHz.load());ddo->setProperty("modRate",dc.modRateHz.load());ddo->setProperty("modDepth",dc.modDepthMs.load());r->setProperty("dualDelay",dd);
    juce::Array<juce::var>sceneArray;auto&sw=audioEngine.getSceneSwitcher();for(int i=0;i<guitardsp::hq::SceneSwitcherHQ::sceneCount;++i){const auto&s=sw.scene(i);auto v=makeObject();auto*o=v.getDynamicObject();o->setProperty("parallel",s.parallelEnabled);o->setProperty("pitch",s.expressionPitchEnabled);o->setProperty("expression",s.expression);o->setProperty("semitones",s.pitchSemitones);o->setProperty("dualDelay",s.dualDelayEnabled);o->setProperty("main",s.mainDb);o->setProperty("clean",s.cleanDb);o->setProperty("sub",s.subDb);juce::Array<juce::var>re,rm;for(int j=0;j<4;++j){re.add(s.pedalEnabled[(size_t)j]);rm.add(s.pedalRouteMask[(size_t)j]);}o->setProperty("pedalEnabled",juce::var(re));o->setProperty("pedalRoutes",juce::var(rm));sceneArray.add(v);}r->setProperty("scenes",juce::var(sceneArray));
    auto mod=makeObject();auto*mo=mod.getDynamicObject();auto&m=rack.modulationControl();mo->setProperty("mode",(int)rack.getModulationMode());mo->setProperty("rate",m.rateHz.load());mo->setProperty("depth",m.depth.load());mo->setProperty("mix",m.mix.load());mo->setProperty("feedback",m.feedback.load());mo->setProperty("manual",m.manual.load());mo->setProperty("shape",m.shape.load());r->setProperty("mod",mod);
    auto de=makeObject();auto*deo=de.getDynamicObject();auto&d=rack.delayControl();deo->setProperty("enabled",rack.isDelayEnabled());deo->setProperty("type",d.flavor.load());deo->setProperty("time",d.timeMs.load());deo->setProperty("feedback",d.feedback.load());deo->setProperty("mix",d.mix.load());deo->setProperty("lowCut",d.lowCutHz.load());deo->setProperty("highCut",d.highCutHz.load());deo->setProperty("drive",d.drive.load());deo->setProperty("wow",d.wow.load());deo->setProperty("flutter",d.flutter.load());deo->setProperty("age",d.age.load());r->setProperty("delay",de);
    auto rvj=makeObject();auto*rvo=rvj.getDynamicObject();auto&rv=rack.reverbControl();rvo->setProperty("enabled",rack.isReverbEnabled());rvo->setProperty("type",rv.flavor.load());rvo->setProperty("size",rv.size.load());rvo->setProperty("decay",rv.decay.load());rvo->setProperty("damping",rv.damping.load());rvo->setProperty("preDelay",rv.preDelayMs.load());rvo->setProperty("mix",rv.mix.load());rvo->setProperty("mod",rv.mod.load());rvo->setProperty("drip",rv.drip.load());r->setProperty("reverb",rvj);
    const auto&cp=audioEngine.getCabMicEngine().getParameters();auto cab=makeObject();auto*co=cab.getDynamicObject();co->setProperty("enabled",audioEngine.getCabMicEngine().isEnabled());co->setProperty("irEngine",(int)cp.irEngine);co->setProperty("cab",(int)cp.cab);co->setProperty("mic",(int)cp.mic);co->setProperty("position",cp.position);co->setProperty("distance",cp.distance);co->setProperty("resonance",cp.resonance);co->setProperty("lowCut",cp.lowCutHz);co->setProperty("highCut",cp.highCutHz);co->setProperty("mix",cp.mix);r->setProperty("cab",cab);return root;
}

bool MainView::applyPreset(const juce::var&preset)
{
    auto*r=preset.getDynamicObject();if(!r)return false;const float in=getFloat(r,"inputGainDb",(float)inputGainSlider.getValue()),out=getFloat(r,"outputGainDb",(float)outputGainSlider.getValue());inputGainSlider.setValue(in,juce::dontSendNotification);outputGainSlider.setValue(out,juce::dontSendNotification);audioEngine.setInputGainDb(in);audioEngine.setOutputGainDb(out);const int am=juce::jlimit(0,1,getInt(r,"ampMode",0));audioEngine.setAmpMode((SignalChain::AmpMode)am);ampModeSelector.setSelectedId(am+1,juce::dontSendNotification);const bool bp=getBool(r,"bypass",false);bypassButton.setToggleState(bp,juce::dontSendNotification);audioEngine.setBypass(bp);audioEngine.setOutputMode((SignalChain::OutputMode)juce::jlimit(0,1,getInt(r,"outputMode",0)));
    auto lv=r->getProperty("legacyStages");if(auto*a=lv.getArray()){auto p=audioEngine.getAmpEngine().getParameters();for(int i=0;i<juce::jmin((int)a->size(),AmpEngine::numStages);++i){auto*o=(*a)[i].getDynamicObject();auto&s=p[(size_t)i];s.preHpHz=getFloat(o,"preHp",s.preHpHz);s.preLpHz=getFloat(o,"preLp",s.preLpHz);s.drive=getFloat(o,"drive",s.drive);s.bias=getFloat(o,"bias",s.bias);s.postLpHz=getFloat(o,"postLp",s.postLpHz);s.output=getFloat(o,"output",s.output);s.nonlinear=getFloat(o,"nonlinear",s.nonlinear);s.clipShape=getFloat(o,"clipShape",s.clipShape);}audioEngine.getAmpEngine().setParameters(p);}
    auto hv=r->getProperty("hqAmp");if(auto*o=hv.getDynamicObject()){auto p=audioEngine.getHQAmpEngine().getParameters();if(auto*a=o->getProperty("stages").getArray())for(int i=0;i<juce::jmin((int)a->size(),20);++i){auto*so=(*a)[i].getDynamicObject();auto&s=p.stage[(size_t)i];s.preHpHz=getFloat(so,"preHp",s.preHpHz);s.preLpHz=getFloat(so,"preLp",s.preLpHz);s.drive=getFloat(so,"drive",s.drive);s.bias=getFloat(so,"bias",s.bias);s.asymmetry=getFloat(so,"asym",s.asymmetry);s.memory=getFloat(so,"memory",s.memory);s.postLpHz=getFloat(so,"postLp",s.postLpHz);s.output=getFloat(so,"output",s.output);}p.bassDb=getFloat(o,"bass",p.bassDb);p.midDb=getFloat(o,"mid",p.midDb);p.trebleDb=getFloat(o,"treble",p.trebleDb);p.sag=getFloat(o,"sag",p.sag);p.sagRecoveryMs=getFloat(o,"sagRecovery",p.sagRecoveryMs);p.damping=getFloat(o,"damping",p.damping);p.presence=getFloat(o,"presence",p.presence);p.biasExcursion=getFloat(o,"biasExcursion",p.biasExcursion);p.transformerSaturation=getFloat(o,"transformerSat",p.transformerSaturation);p.outputDb=getFloat(o,"outputDb",p.outputDb);audioEngine.getHQAmpEngine().setParameters(p);}
    auto&rack=audioEngine.getHQEffectsRack();if(auto*a=r->getProperty("pedals").getArray())for(int i=0;i<juce::jmin((int)a->size(),guitardsp::hq::HQEffectsRack::pedalSlots);++i){auto*o=(*a)[i].getDynamicObject();auto&p=rack.pedalSlot(i);p.enabled.store(getBool(o,"enabled",p.enabled.load()));p.model.store(juce::jlimit(0,9,getInt(o,"model",p.model.load())));p.drive.store(getFloat(o,"drive",p.drive.load()));p.tone.store(getFloat(o,"tone",p.tone.load()));p.levelDb.store(getFloat(o,"level",p.levelDb.load()));p.mix.store(getFloat(o,"mix",p.mix.load()));p.aux1.store(getFloat(o,"aux1",p.aux1.load()));p.aux2.store(getFloat(o,"aux2",p.aux2.load()));p.aux3.store(getFloat(o,"aux3",p.aux3.load()));p.routeMask.store(juce::jlimit(0,7,getInt(o,"routeMask",p.routeMask.load())));}
    if(auto*o=r->getProperty("gate").getDynamicObject()){auto&g=rack.gateControl();rack.setDynamicsMode((guitardsp::hq::HQEffectsRack::DynamicsMode)juce::jlimit(0,3,getInt(o,"mode",(int)rack.getDynamicsMode())));g.thresholdDb.store(getFloat(o,"threshold",g.thresholdDb.load()));g.rangeDb.store(getFloat(o,"range",g.rangeDb.load()));g.ratio.store(getFloat(o,"ratio",g.ratio.load()));g.attackMs.store(getFloat(o,"attack",g.attackMs.load()));g.holdMs.store(getFloat(o,"hold",g.holdMs.load()));g.releaseMs.store(getFloat(o,"release",g.releaseMs.load()));g.hysteresisDb.store(getFloat(o,"hysteresis",g.hysteresisDb.load()));g.sidechainHpHz.store(getFloat(o,"hp",g.sidechainHpHz.load()));g.sidechainLpHz.store(getFloat(o,"lp",g.sidechainLpHz.load()));}
    if(auto*o=r->getProperty("guitarComp").getDynamicObject()){auto&c=rack.guitarCompControl();c.sustain.store(getFloat(o,"sustain",c.sustain.load()));c.attack.store(getFloat(o,"attack",c.attack.load()));c.blend.store(getFloat(o,"blend",c.blend.load()));c.levelDb.store(getFloat(o,"level",c.levelDb.load()));}
    if(auto*o=r->getProperty("parallelRig").getDynamicObject()){auto&c=rack.parallelRigControl();c.enabled.store(getBool(o,"enabled",c.enabled.load()));c.autoLatencyComp.store(getBool(o,"autoLatency",c.autoLatencyComp.load()));c.mainLevelDb.store(getFloat(o,"mainLevel",c.mainLevelDb.load()));c.mainDelayMs.store(getFloat(o,"mainDelay",c.mainDelayMs.load()));c.cleanEnabled.store(getBool(o,"cleanEnabled",c.cleanEnabled.load()));c.cleanLevelDb.store(getFloat(o,"cleanLevel",c.cleanLevelDb.load()));c.cleanHpHz.store(getFloat(o,"cleanHp",c.cleanHpHz.load()));c.cleanLpHz.store(getFloat(o,"cleanLp",c.cleanLpHz.load()));c.cleanPresenceDb.store(getFloat(o,"cleanPresence",c.cleanPresenceDb.load()));c.cleanDrive.store(getFloat(o,"cleanDrive",c.cleanDrive.load()));c.cleanBassDb.store(getFloat(o,"cleanBass",c.cleanBassDb.load()));c.cleanMidDb.store(getFloat(o,"cleanMid",c.cleanMidDb.load()));c.cleanTrebleDb.store(getFloat(o,"cleanTreble",c.cleanTrebleDb.load()));c.cleanDelayMs.store(getFloat(o,"cleanDelay",c.cleanDelayMs.load()));c.cleanInvert.store(getBool(o,"cleanInvert",c.cleanInvert.load()));c.subEnabled.store(getBool(o,"subEnabled",c.subEnabled.load()));c.subLevelDb.store(getFloat(o,"subLevel",c.subLevelDb.load()));c.subHpHz.store(getFloat(o,"subHp",c.subHpHz.load()));c.subLpHz.store(getFloat(o,"subLp",c.subLpHz.load()));c.subBodyDb.store(getFloat(o,"subBody",c.subBodyDb.load()));c.subDrive.store(getFloat(o,"subDrive",c.subDrive.load()));c.subBassDb.store(getFloat(o,"subBass",c.subBassDb.load()));c.subMidDb.store(getFloat(o,"subMid",c.subMidDb.load()));c.subTrebleDb.store(getFloat(o,"subTreble",c.subTrebleDb.load()));c.subTracking.store(getFloat(o,"subTracking",c.subTracking.load()));c.subTone.store(getFloat(o,"subTone",c.subTone.load()));c.subSmooth.store(getFloat(o,"subSmooth",c.subSmooth.load()));c.subDelayMs.store(getFloat(o,"subDelay",c.subDelayMs.load()));c.subInvert.store(getBool(o,"subInvert",c.subInvert.load()));}
    if(auto*o=r->getProperty("inputLoading").getDynamicObject()){auto&c=audioEngine.getInputLoadingControl();c.enabled.store(getBool(o,"enabled",c.enabled.load()));c.pickupResistanceOhm.store(getFloat(o,"pickupR",c.pickupResistanceOhm.load()));c.pickupInductanceH.store(getFloat(o,"pickupL",c.pickupInductanceH.load()));c.cableCapacitancePf.store(getFloat(o,"cableC",c.cableCapacitancePf.load()));c.inputImpedanceOhm.store(getFloat(o,"inputZ",c.inputImpedanceOhm.load()));c.trimDb.store(getFloat(o,"trim",c.trimDb.load()));}
    if(auto*o=r->getProperty("expressionPitch").getDynamicObject()){auto&c=audioEngine.getExpressionPitchControl();c.enabled.store(getBool(o,"enabled",c.enabled.load()));c.routeMask.store(juce::jlimit(0,7,getInt(o,"routeMask",c.routeMask.load())));c.semitones.store(getFloat(o,"semitones",c.semitones.load()));c.expression.store(getFloat(o,"expression",c.expression.load()));c.wet.store(getFloat(o,"wet",c.wet.load()));c.dry.store(getFloat(o,"dry",c.dry.load()));c.tracking.store(getFloat(o,"tracking",c.tracking.load()));c.tone.store(getFloat(o,"tone",c.tone.load()));c.smooth.store(getFloat(o,"smooth",c.smooth.load()));}
    if(auto*o=r->getProperty("dualDelay").getDynamicObject()){auto&c=audioEngine.getDualDelayControl();c.enabled.store(getBool(o,"enabled",c.enabled.load()));c.timeLms.store(getFloat(o,"timeL",c.timeLms.load()));c.timeRms.store(getFloat(o,"timeR",c.timeRms.load()));c.feedbackL.store(getFloat(o,"feedbackL",c.feedbackL.load()));c.feedbackR.store(getFloat(o,"feedbackR",c.feedbackR.load()));c.crossFeedback.store(getFloat(o,"crossFeedback",c.crossFeedback.load()));c.mix.store(getFloat(o,"mix",c.mix.load()));c.lowCutHz.store(getFloat(o,"lowCut",c.lowCutHz.load()));c.highCutHz.store(getFloat(o,"highCut",c.highCutHz.load()));c.modRateHz.store(getFloat(o,"modRate",c.modRateHz.load()));c.modDepthMs.store(getFloat(o,"modDepth",c.modDepthMs.load()));}
    if(auto*a=r->getProperty("scenes").getArray()){auto&sw=audioEngine.getSceneSwitcher();for(int i=0;i<juce::jmin((int)a->size(),guitardsp::hq::SceneSwitcherHQ::sceneCount);++i){auto*o=(*a)[i].getDynamicObject();auto&s=sw.scene(i);s.parallelEnabled=getBool(o,"parallel",s.parallelEnabled);s.expressionPitchEnabled=getBool(o,"pitch",s.expressionPitchEnabled);s.expression=getFloat(o,"expression",s.expression);s.pitchSemitones=getFloat(o,"semitones",s.pitchSemitones);s.dualDelayEnabled=getBool(o,"dualDelay",s.dualDelayEnabled);s.mainDb=getFloat(o,"main",s.mainDb);s.cleanDb=getFloat(o,"clean",s.cleanDb);s.subDb=getFloat(o,"sub",s.subDb);if(auto*e=o->getProperty("pedalEnabled").getArray())for(int j=0;j<juce::jmin(4,(int)e->size());++j)s.pedalEnabled[(size_t)j]=(bool)(*e)[j];if(auto*m=o->getProperty("pedalRoutes").getArray())for(int j=0;j<juce::jmin(4,(int)m->size());++j)s.pedalRouteMask[(size_t)j]=(int)(*m)[j];}}
    if(auto*o=r->getProperty("mod").getDynamicObject()){auto&m=rack.modulationControl();rack.setModulationMode((guitardsp::hq::HQEffectsRack::ModulationMode)juce::jlimit(0,5,getInt(o,"mode",(int)rack.getModulationMode())));m.rateHz.store(getFloat(o,"rate",m.rateHz.load()));m.depth.store(getFloat(o,"depth",m.depth.load()));m.mix.store(getFloat(o,"mix",m.mix.load()));m.feedback.store(getFloat(o,"feedback",m.feedback.load()));m.manual.store(getFloat(o,"manual",m.manual.load()));m.shape.store(getFloat(o,"shape",m.shape.load()));}
    if(auto*o=r->getProperty("delay").getDynamicObject()){auto&d=rack.delayControl();rack.setDelayEnabled(getBool(o,"enabled",rack.isDelayEnabled()));d.flavor.store(juce::jlimit(0,2,getInt(o,"type",d.flavor.load())));d.timeMs.store(getFloat(o,"time",d.timeMs.load()));d.feedback.store(getFloat(o,"feedback",d.feedback.load()));d.mix.store(getFloat(o,"mix",d.mix.load()));d.lowCutHz.store(getFloat(o,"lowCut",d.lowCutHz.load()));d.highCutHz.store(getFloat(o,"highCut",d.highCutHz.load()));d.drive.store(getFloat(o,"drive",d.drive.load()));d.wow.store(getFloat(o,"wow",d.wow.load()));d.flutter.store(getFloat(o,"flutter",d.flutter.load()));d.age.store(getFloat(o,"age",d.age.load()));}
    if(auto*o=r->getProperty("reverb").getDynamicObject()){auto&v=rack.reverbControl();rack.setReverbEnabled(getBool(o,"enabled",rack.isReverbEnabled()));v.flavor.store(juce::jlimit(0,3,getInt(o,"type",v.flavor.load())));v.size.store(getFloat(o,"size",v.size.load()));v.decay.store(getFloat(o,"decay",v.decay.load()));v.damping.store(getFloat(o,"damping",v.damping.load()));v.preDelayMs.store(getFloat(o,"preDelay",v.preDelayMs.load()));v.mix.store(getFloat(o,"mix",v.mix.load()));v.mod.store(getFloat(o,"mod",v.mod.load()));v.drip.store(getFloat(o,"drip",v.drip.load()));}
    if(auto*o=r->getProperty("cab").getDynamicObject()){auto p=audioEngine.getCabMicEngine().getParameters();p.irEngine=(guitardsp::hq::CabIrEngine)juce::jlimit(0,1,getInt(o,"irEngine",(int)p.irEngine));p.cab=(guitardsp::hq::CabType)juce::jlimit(0,3,getInt(o,"cab",(int)p.cab));p.mic=(guitardsp::hq::MicType)juce::jlimit(0,2,getInt(o,"mic",(int)p.mic));p.position=getFloat(o,"position",p.position);p.distance=getFloat(o,"distance",p.distance);p.resonance=getFloat(o,"resonance",p.resonance);p.lowCutHz=getFloat(o,"lowCut",p.lowCutHz);p.highCutHz=getFloat(o,"highCut",p.highCutHz);p.mix=getFloat(o,"mix",p.mix);audioEngine.getCabMicEngine().setParameters(p);audioEngine.getCabMicEngine().setEnabled(getBool(o,"enabled",audioEngine.getCabMicEngine().isEnabled()));}
    refreshPagesFromEngine();return true;
}

void MainView::saveCurrentPreset(){auto n=presetSelector.getText().trim();if(n.isEmpty()||n=="Type preset name")n="Preset 1";if(getPresetFile(n).replaceWithText(juce::JSON::toString(capturePreset(),false)))refreshPresetList(n);}
void MainView::loadSelectedPreset(){auto n=presetSelector.getText().trim();auto f=getPresetFile(n);if(!f.existsAsFile())return;auto p=juce::JSON::parse(f.loadFileAsString());if(applyPreset(p))presetSelector.setText(n,juce::dontSendNotification);}
void MainView::deleteSelectedPreset(){auto f=getPresetFile(presetSelector.getText().trim());if(f.existsAsFile())f.deleteFile();refreshPresetList();}
void MainView::refreshPagesFromEngine(){ampPage.refreshFromEngine();pedalPage.refreshFromEngine();cabPage.refreshFromEngine();effectsPage.refreshFromEngine();performancePage.refreshFromEngine();}
void MainView::paint(juce::Graphics&g){g.fillAll(juce::Colour::fromRGB(9,12,16));auto r=getLocalBounds();auto h=r.removeFromTop(76);g.setColour(juce::Colour::fromRGB(14,18,24));g.fillRect(h);g.setColour(juce::Colours::white);g.setFont(juce::Font(24.0f,juce::Font::bold));g.drawText("GuitarDSP-Pro",h.removeFromLeft(250).reduced(20,0),juce::Justification::centredLeft);g.setColour(juce::Colour::fromRGB(222,110,58));g.setFont(juce::Font(13.0f));g.drawText("MULTI-RIG / SAFE OUTPUT",h.removeFromLeft(210),juce::Justification::centredLeft);g.setColour(juce::Colour::fromRGB(12,16,21));g.fillRect(0,76,getWidth(),38);}
void MainView::resized(){auto r=getLocalBounds();auto h=r.removeFromTop(76);auto c=h.removeFromRight(845).reduced(8);inputLabel.setBounds(c.removeFromLeft(48));inputGainSlider.setBounds(c.removeFromLeft(170).reduced(3,10));inputMeterLabel.setBounds(c.removeFromLeft(70));c.removeFromLeft(5);outputLabel.setBounds(c.removeFromLeft(58));outputGainSlider.setBounds(c.removeFromLeft(170).reduced(3,10));outputMeterLabel.setBounds(c.removeFromLeft(70));ampModeSelector.setBounds(c.removeFromLeft(135).reduced(4,10));bypassButton.setBounds(c.removeFromLeft(90).reduced(5,10));auto pb=r.removeFromTop(38).reduced(14,4);presetLabel.setBounds(pb.removeFromLeft(58));presetSelector.setBounds(pb.removeFromLeft(260));pb.removeFromLeft(6);presetSaveButton.setBounds(pb.removeFromLeft(72));pb.removeFromLeft(6);presetDeleteButton.setBounds(pb.removeFromLeft(82));navigation.setBounds(r.removeFromTop(54));if(visiblePage)visiblePage->setBounds(r.reduced(14));}
void MainView::showPage(NavigationBar::Page p){juce::Component*n=nullptr;switch(p){case NavigationBar::Page::amp:n=&ampPage;break;case NavigationBar::Page::pedal:n=&pedalPage;break;case NavigationBar::Page::cab:n=&cabPage;break;case NavigationBar::Page::effects:n=&effectsPage;break;case NavigationBar::Page::performance:n=&performancePage;break;case NavigationBar::Page::settings:n=&settingsPage;break;}if(visiblePage)visiblePage->setVisible(false);visiblePage=n;if(visiblePage){visiblePage->setVisible(true);visiblePage->toFront(false);}resized();}
void MainView::timerCallback(){const float i=juce::jmax(audioEngine.getInputPeak(0),audioEngine.getInputPeak(1)),o=juce::jmax(audioEngine.getOutputPeak(0),audioEngine.getOutputPeak(1));inputMeterLabel.setText(juce::String(i,1)+" dB",juce::dontSendNotification);outputMeterLabel.setText(juce::String(o,1)+" dB",juce::dontSendNotification);}
